# Generated by Django 3.0.7 on 2020-07-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='cities',
            name='temperature',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Temprature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=200, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.Cities')),
            ],
        ),
    ]
