# Generated by Django 3.0.7 on 2020-07-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200706_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='temperature',
        ),
        migrations.DeleteModel(
            name='Temprature',
        ),
    ]
